### ISSUE TITLE
开源预告

### ISSUE THREAD

**Issue by huntbao** [x-orpheus/nei#1]
[NEI](https://nei.netease.com/) 是一款接口管理平台的产品，相信对本文有兴趣的朋友已经对接口管理平台的功能、价值、国内外竞品等等有所了解，所以本文也不会在这些地方展开讲解。今天我们只讲为什么 NEI 会选择开源。

可以毫不谦虚的说，NEI 在同类产品中做得还算是比较成功的。截止目前，NEI 的注册用户超过 2万2千（包括网易公司内部用户以及外部公司用户，NEI 一直对外开放免费使用），接口数量超过 23 万，数据模型数量超过 28 万，内部产品（NEI 中接口数量超过 100 个的项目组）有 140 个之多，外部产品有 270 个之多。

NEI 的成功离不开公司的大力支持。要知道，NEI 不是一款商业软件，它并不以赢利为目标，能在这样的项目上持续投入开发资源，放眼国内外公司并不多见。之前在和公司外部的 NEI 用户聊，有人说 NEI 的 UI 比较好看，国内竞品的界面好看的确实不多，毕竟 NEI 的初始版本邀请了专业设计师参与设计。还有人说羡慕网易这样的大公司，基础设施完善，大家可以在同个平台上协同作业，我想他是已经遇到了接口管理方面的难题了。类似的聊天场景还有很多，相信他们或多或少都遇到了或者是意识到了接口管理对于研发团队的意义。

几乎所有的外部用户都在询问 NEI 是否可以私有部署。不管是什么类型的产品，它的 API 接口相对来说都是私密数据，因为其中会涉及到业务逻辑。NEI 一直没有提供免费或者是付费的私有部署版本，这也让非常多的外部公司用户望而却步。

那么今天 NEI 为什么要选择直接开源呢？下面说说我们的看法。

首先，目前 NEI 功能完备运行稳定，该有的功能基本上都有了，产品迭代速度放缓，主要以公司内部用户的需求为主。所以，当外部用户提了需求后，除非是影响使用的或者公司内部也有相同的需求，否则很难保证能及时响，这一点相信会让所有技术人员自责。

其次，个性化需求永远存在，作为一款非商业软件，没有必要也不太可能一直投入资源去开发特定场景下的功能，我们决定把这个权力交给用户自己，让他们去定制符合自己的功能。

第三，网易内部研发团队的实践已经证明，NEI 确实可以提升研发团队的工作效率，好的软件要共享给所有开发人员。

第四，NEI 的设计思想更多地是为了满足网易公司内部的研发习惯，开源之后，我们相信会有很多有才的工程师来给 NEI 添砖加瓦，这对于 NEI 软件本身的发展以及接口管理的最佳实践都是非常有利的。

基于上述考虑，我们决定将 NEI 开源，因为要将项目开源还有一定的改造工作和必需的文档，具体的开源时间请关注后续的公告，请各位同行朋友拭目以待。

如果大家有什么需求或者疑问，请在下方留言，谢谢。

—— 网易云音乐前端研发团队 2020.3.11

**Comment by Suzichen** [comment]
期待

**Comment by cnHuaShao** [comment]
持续关注

**Comment by JZLeung** [comment]
期待NEI的开源。


PS： 如果有官方的 docker 部署就最好了。

**Comment by abel1314520** [comment]
有大概时间点吗？  希望早点放出

**Comment by ansonhorse** [comment]
想了解一下有用到哪些技术

**Comment by huntbao** [comment]
> 有大概时间点吗？ 希望早点放出

快了

**Comment by huntbao** [comment]
> 想了解一下有用到哪些技术

前端：[NEJ](https://github.com/genify/nej)、[Regularjs](https://github.com/regularjs/regular)
后端：Node.js（Koa）
数据库：MySQL、Redis、MongoDB、

**Comment by huntbao** [comment]
源码已上传

**Comment by cnHuaShao** [comment]
马上安装试一下
