### ISSUE TITLE
私有部署中文乱码

### ISSUE THREAD

**Issue by TaroXin** [x-orpheus/nei#11]
**Bug 描述**
接口的状态是乱码的，但是如果改变状态，会出现中文，刷新后又回到乱码状态

**截图**
![image](https://user-images.githubusercontent.com/19855713/81634554-c65d2680-9441-11ea-84cd-3863f5ae3c80.png)

![image](https://user-images.githubusercontent.com/19855713/81634580-d412ac00-9441-11ea-9ca1-eb0f4c66c46e.png)

![image](https://user-images.githubusercontent.com/19855713/81634597-de34aa80-9441-11ea-85f3-0676de78e7bc.png)

**Comment by huntbao** [comment]
数据库里面的值看下是不是乱码？

**Comment by TaroXin** [comment]
> 数据库里面的值看下是不是乱码？

![image](https://user-images.githubusercontent.com/19855713/81775122-ba936200-951e-11ea-9507-6badc728b670.png)


数据库好像也是乱码

**Comment by huntbao** [comment]
那就是数据库编码设置得不对吧？

**Comment by lilywang711** [comment]
这个问题我也遇到了，似乎是因为部署 online 环境的初始化数据库表的命令的编码设置的不对（`server/dao`路径下的那些 `** Dao.js`）（这里的代码不是很懂，具体原因不清楚）。
解决办法是你可以试着把 `docs/install.sql`里的语句去  mysql 里执行一遍。就可以了。

**Comment by lilywang711** [comment]
By the way 请问一下，如果不执行 docs/install.sql. online 环境的 mysql 初始化表是在哪里执行的呢？是怎么个流程呢？

**Comment by huntbao** [comment]
> By the way 请问一下，如果不执行 docs/install.sql. online 环境的 mysql 初始化表是在哪里执行的呢？是怎么个流程呢？

这个就是需要手动执行的，`docs/install.sql` 这个只是表结构文件。

**Comment by lilywang711** [comment]
> > By the way 请问一下，如果不执行 docs/install.sql. online 环境的 mysql 初始化表是在哪里执行的呢？是怎么个流程呢？
> 
> 这个就是需要手动执行的，`docs/install.sql` 这个只是表结构文件。

可是通过 docker 部署到线上去后，我没有手动去执行过 `docs/install.sql` ，那些表就有了。

**Comment by lilywang711** [comment]
> > By the way 请问一下，如果不执行 docs/install.sql. online 环境的 mysql 初始化表是在哪里执行的呢？是怎么个流程呢？
> 
> 这个就是需要手动执行的，`docs/install.sql` 这个只是表结构文件。

在本地 `npm run dev `的时候确实是需要手动执行。

**Comment by int64ago** [comment]
确认下你的 mysql 编码

`show variables like '%char%';`

如果编码不是 utf8mb4 那就是有问题了，可以通过启动参数 `--character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci` 设置，也可以通过配置文件 my.conf 设置：

```
[client]
default-character-set=utf8mb4

[mysql]
default-character-set=utf8mb4

[mysqld]
character-set-server=utf8mb4
collation-server=utf8mb4_general_ci
```

**Comment by lilywang711** [comment]
> 确认下你的 mysql 编码
> 
> `show variables like '%char%';`
> 
> 如果编码不是 utf8mb4 那就是有问题了，可以通过启动参数 `--character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci` 设置，也可以通过配置文件 my.conf 设置：
> 
> ```
> [client]
> default-character-set=utf8mb4
> 
> [mysql]
> default-character-set=utf8mb4
> 
> [mysqld]
> character-set-server=utf8mb4
> collation-server=utf8mb4_general_ci
> ```

感谢回复。
输入`show variables like '%char%';`后确实看到几个都是 latin1
可是 `docker-compose.yaml` 里 mysql command 加了这两句呀
show variables like '%char%';

![image](https://user-images.githubusercontent.com/17040010/82001736-76bf6a80-968e-11ea-81e9-e19e11a1e7dd.png)

**Comment by int64ago** [comment]
> 可是通过 docker 部署到线上去后，我没有手动去执行过 `docs/install.sql` ，那些表就有了。

[这里](https://github.com/x-orpheus/nei/blob/master/docker-compose.yaml#L30) 帮你做了

**Comment by int64ago** [comment]
> > 确认下你的 mysql 编码
> > `show variables like '%char%';`
> > 如果编码不是 utf8mb4 那就是有问题了，可以通过启动参数 `--character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci` 设置，也可以通过配置文件 my.conf 设置：
> > ```
> > [client]
> > default-character-set=utf8mb4
> > 
> > [mysql]
> > default-character-set=utf8mb4
> > 
> > [mysqld]
> > character-set-server=utf8mb4
> > collation-server=utf8mb4_general_ci
> > ```
> 
> 感谢回复。
> 输入`show variables like '%char%';`后确实看到几个都是 latin1
> 可是 `docker-compose.yaml` 里 mysql command 加了这两句呀
> 
> ![image](https://user-images.githubusercontent.com/17040010/82001736-76bf6a80-968e-11ea-81e9-e19e11a1e7dd.png)

把 `.nei` 文件夹删了重新来一次吧，可能是中途干了啥污染了配置？

**Comment by TaroXin** [comment]
目前来看是数据库引起的，我是直接修改了数据库中的值，然后重启 `docker-compose`，网站上面就正常了

**Comment by int64ago** [comment]
#12 修了

问题是因为初始化脚本初始化插入数据时编码的问题，数据本身编码是 OK 的

你可以更新下代码，然后删除 `~/.nei` 这个目录后重新再来一遍，就都 ok 了
