### ISSUE TITLE
new (winston.Logger)在使用的winston版本为3.2.1以上版本时会提示错误

### ISSUE THREAD

**Issue by cnHuaShao** [x-orpheus/nei#2]
**new (winston.Logger)在使用的winston版本为3.2.1以上版本时会提示错误**

**在使用高版本时修订方式**
编辑server/util/log.js文件，使用 winston.createLogger 代替 new (winston.Logger)

**软件环境**
 - 操作系统及版本:centos8 x86
 - Node及版本: 13.N

**Comment by huntbao** [comment]
默认安装不会安装这个版本的吧？后续我们可以考虑升级一下。谢谢反馈。

**Comment by cnHuaShao** [comment]
默认安装下不会出现这个错误，手动安装相关缺失组件时会出现
