### ISSUE TITLE
docker 部署出错 (安装 nej 时 )

### ISSUE THREAD

**Issue by lilywang711** [x-orpheus/nei#9]
**Bug 描述**
精简的 Bug 描述。
The command '/bin/sh -c npm install nej -g' returned a non-zero code: 1
**重现步骤**
1. docker-compose up -d
2. bug 重现

**期望结果**
精简的期望描述。
期望能通过 docker 部署成功
**截图**
有截图就是最好的。
![image](https://user-images.githubusercontent.com/17040010/80618178-9131fb00-8a75-11ea-905b-cb60aae3749a.png)

**软件环境**
 - 操作系统及版本: 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
 - Node及版本: 无需
 - 浏览器及版本: 无需

**其他信息**
其他信息可以填这里。
单独安装 nej 时也会报以下错误
![image](https://user-images.githubusercontent.com/17040010/80619237-03570f80-8a77-11ea-85a2-284ba00b3b7d.png)

**Comment by int64ago** [comment]
这个就单纯的 npm 安装校验问题，我们这边无法复现，不过看了下这个问题还比较多，你可以尝试

https://stackoverflow.com/questions/47545940/when-i-run-npm-install-it-returns-with-err-code-eintegrity-npm-5-3-0

里说的

`npm cache verify` （需要写到 Dockerfile 里）

当然，也可能是淘宝源的问题，可以尝试去掉淘宝源的设置

**Comment by lilywang711** [comment]
果然，是淘宝源的问题，谢谢
